import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
    title: {
        absolute: "ACE365 গেমস - উচ্চ জয়ের হার সহ সম্পূর্ণ সংগ্রহ",
      },
    description: "ACE365 হল বাংলাদেশে অনলাইনে ক্যাসিনো গেম খেলার জন্য সবচেয়ে মজাদার এবং স্মার্ট বেট প্ল্যাটফর্মগুলির মধ্যে একটি, স্বাগত বোনাস দাবি করতে এখনই লগইন করুন এবং সাইন আপ করুন।",
    alternates: {
        canonical: "https://www.ace-365.net/games",
    },
};

export default function GamesLayout({ children }: { children: ReactNode }) {
    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "CollectionPage",
                        "@id": "https://www.ace-365.net/games/#collectionpage",
                        name: "ACE365 গেমস - উচ্চ জয়ের হার সহ সম্পূর্ণ সংগ্রহ",
                        description: "আমাদের ক্যাসিনো গেম, স্লট, পোকার এবং স্পোর্টস বেটিং বিকল্পগুলির বিস্তৃত সংগ্রহ ব্রাউজ করুন।",
                        url: "https://www.ace-365.net/games",
                        isPartOf: {
                            "@id": "https://www.ace-365.net/#website",
                        },
                        breadcrumb: {
                            "@type": "BreadcrumbList",
                            itemListElement: [
                                {
                                    "@type": "ListItem",
                                    position: 1,
                                    name: "Home",
                                    item: "https://www.ace-365.net/",
                                },
                                {
                                    "@type": "ListItem",
                                    position: 2,
                                    name: "Games",
                                    item: "https://www.ace-365.net/games",
                                },
                            ],
                        },
                        mainEntity: [
                            {
                                "@type": "ItemList",
                                "@id": "https://www.ace-365.net/games/#slotslist",
                                name: "জনপ্রিয় স্লট গেম",
                                description: "ACE365 সবচেয়ে জনপ্রিয় স্লট গেম",
                                numberOfItems: 5,
                                itemListOrder: "Descending",
                                itemListElement: [
                                    {
                                        "@type": "ListItem",
                                        position: 1,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#aviator",
                                            name: "Aviator",
                                            description: "অবিশ্বাস্য উচ্চতায় পৌঁছাতে পারে এমন মাল্টিপ্লায়ার সহ জনপ্রিয় অ্যাভিয়েটর ক্র্যাশ গেমের রোমাঞ্চ উপভোগ করুন।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/slots/aviator.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.9",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "1245",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 2,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#bonanza2",
                                            name: "Bonanza 2",
                                            description: "জনপ্রিয় সুইট বোনানজা স্লটের সিক্যুয়েল, যেখানে আরও বেশি উত্তেজনাপূর্ণ বৈশিষ্ট্য এবং আরও বড় জয়ের সম্ভাবনা রয়েছে।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/slots/sweet-bonanza2.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.8",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "987",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 3,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#olympus2",
                                            name: "Olympus 2",
                                            description: "বিশাল গুণক সম্ভাবনা সহ এই উচ্চ-অস্থিরতা স্লটে দেবতাদের রাজ্যে প্রবেশ করুন।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/slots/gates-olympus2.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.7",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "856",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 4,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#crazy777",
                                            name: "Crazy 777",
                                            description: "আধুনিক মোড় সহ একটি ক্লাসিক স্লট, যেখানে আইকনিক 777 প্রতীক এবং উত্তেজনাপূর্ণ বোনাস বৈশিষ্ট্য রয়েছে।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/slots/crazy777.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.3",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "723",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 5,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#alibaba",
                                            name: "Alibaba",
                                            description: "এই JILI-চালিত স্লটটিতে আলিবাবার সাথে তার অ্যাডভেঞ্চারে যোগ দিন যেখানে রয়েছে আকর্ষণীয় বোনাস রাউন্ড এবং ফ্রি স্পিন।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/slots/alibaba.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.5",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "678",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                ],
                            },
                            {
                                "@type": "ItemList",
                                "@id": "https://www.ace-365.net/games/#casinolist",
                                name: "Popular Casino Games",
                                description: "Most popular casino table games at ACE365",
                                numberOfItems: 5,
                                itemListOrder: "Descending",
                                itemListElement: [
                                    {
                                        "@type": "ListItem",
                                        position: 1,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#baccarat6",
                                            name: "Baccarat 6",
                                            description: "নির্দিষ্ট হাতের সংমিশ্রণের জন্য উন্নত অর্থপ্রদান সহ প্রিমিয়াম ব্যাকার্যাট অভিজ্ঞতা।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/casino/baccarat6.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.9",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "1102",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 2,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#andarbahar",
                                            name: "Andar Bahar",
                                            description: "সহজ নিয়ম এবং দ্রুতগতির গেমপ্লে সহ জনপ্রিয় ভারতীয় কার্ড গেম।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/casino/andar-bahar.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.8",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "943",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 3,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#crazytime",
                                            name: "Crazy Time",
                                            description: "একাধিক বোনাস রাউন্ড এবং বড় জয়ের সম্ভাবনা সহ একটি উত্তেজনাপূর্ণ গেম শো-স্টাইলের ক্যাসিনো গেম।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/casino/crazy-time.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.2",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "876",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 4,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#blackjackvip",
                                            name: "Blackjack VIP",
                                            description: "ভিআইপি খেলোয়াড়দের জন্য উচ্চ সীমা এবং এক্সক্লুসিভ বৈশিষ্ট্য সহ প্রিমিয়াম ব্ল্যাকজ্যাক অভিজ্ঞতা।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/casino/blackjackVIP.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.5",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "654",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 5,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#royalpoker",
                                            name: "Royal Poker",
                                            description: "বিশেষ রয়্যাল ফ্লাশ বোনাস এবং উন্নত গেমপ্লে সহ এক্সক্লুসিভ পোকার ভেরিয়েন্ট।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/casino/royal-poker.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.8",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "789",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                ],
                            },
                            {
                                "@type": "ItemList",
                                "@id": "https://www.ace-365.net/games/#pokerlist",
                                name: "Popular Poker Games",
                                description: "ACE365 সবচেয়ে জনপ্রিয় পোকার ভেরিয়েন্টগুলি",
                                numberOfItems: 3,
                                itemListOrder: "Descending",
                                itemListElement: [
                                    {
                                        "@type": "ListItem",
                                        position: 1,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#teenpatti",
                                            name: "Teen Patti",
                                            description: "ACE365 সবচেয়ে জনপ্রিয় পোকার ভেরিয়েন্টগুলি",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/poker/teen-patti.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.2",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "1320",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 2,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#blackjack",
                                            name: "Blackjack",
                                            description: "স্ট্যান্ডার্ড নিয়ম এবং প্রতিযোগিতামূলক গেমপ্লে সহ ক্লাসিক ব্ল্যাকজ্যাক পোকার ভেরিয়েন্ট।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/poker/blackjack.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.8",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "965",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 3,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#callbreak",
                                            name: "Callbreak",
                                            description: "কৌশলগত গেমপ্লে সহ জনপ্রিয় দক্ষিণ এশীয় কৌশল-গ্রহণ কার্ড গেম।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/poker/callbreak.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.5",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "843",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                ],
                            },
                            {
                                "@type": "ItemList",
                                "@id": "https://www.ace-365.net/games/#fishinglist",
                                name: "Popular Fishing Games",
                                description: "ACE365 সবচেয়ে জনপ্রিয় মাছ ধরার গেম",
                                numberOfItems: 2,
                                itemListOrder: "Descending",
                                itemListElement: [
                                    {
                                        "@type": "ListItem",
                                        position: 1,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#monkeyking",
                                            name: "Monkey King",
                                            description: "বিশেষ ক্ষমতা সম্পন্ন কিংবদন্তি বানর রাজা চরিত্রের সমন্বিত আকর্ষণীয় মাছ ধরার খেলা।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/fishing/monkey-king.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.5",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "732",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 2,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#zodiachunter",
                                            name: "Zodiac Hunter",
                                            description: "বিশেষ ক্ষমতা এবং পুরষ্কার সহ রাশিচক্র-থিমযুক্ত প্রাণীদের নিয়ে মাছ ধরার খেলা।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Casino Game",
                                            image: "https://www.ace-365.net/images/game/fishing/zodiac-hunter.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.9",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "621",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                ],
                            },
                            {
                                "@type": "ItemList",
                                "@id": "https://www.ace-365.net/games/#sportslist",
                                name: "Popular Sports Games",
                                description: "ACE365 সর্বাধিক জনপ্রিয় স্পোর্টস বেটিং গেম",
                                numberOfItems: 2,
                                itemListOrder: "Descending",
                                itemListElement: [
                                    {
                                        "@type": "ListItem",
                                        position: 1,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#cricket",
                                            name: "Cricket",
                                            description: "লাইভ ম্যাচ এবং প্রতিযোগিতামূলক সম্ভাবনা সহ বিস্তৃত ক্রিকেট বেটিং প্ল্যাটফর্ম।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Sports Game",
                                            image: "https://www.ace-365.net/images/game/sports/cricket.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.9",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "1543",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                    {
                                        "@type": "ListItem",
                                        position: 2,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#soccer",
                                            name: "Soccer",
                                            description: "বিশ্বব্যাপী প্রধান লীগ এবং টুর্নামেন্ট কভার করে সম্পূর্ণ ফুটবল বেটিং প্ল্যাটফর্ম।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Sports Game",
                                            image: "https://www.ace-365.net/images/game/sports/soccer.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.9",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "1287",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                ],
                            },
                            {
                                "@type": "ItemList",
                                "@id": "https://www.ace-365.net/games/#esportslist",
                                name: "Popular Esports Games",
                                description: "ACE365 সবচেয়ে জনপ্রিয় ই-স্পোর্টস বেটিং বিকল্পগুলি",
                                numberOfItems: 1,
                                itemListOrder: "Descending",
                                itemListElement: [
                                    {
                                        "@type": "ListItem",
                                        position: 1,
                                        item: {
                                            "@type": "SoftwareApplication",
                                            "@id": "https://www.ace-365.net/games/#svenus",
                                            name: "SVenus",
                                            description: "প্রতিযোগিতামূলক সম্ভাবনা এবং লাইভ স্ট্রিমিং সহ প্রিমিয়াম ইস্পোর্টস বেটিং প্ল্যাটফর্ম।",
                                            operatingSystem: "Web Browser, Android, iOS",
                                            applicationCategory: "GameApplication",
                                            applicationSubCategory: "Esports Game",
                                            image: "https://www.ace-365.net/images/game/esports/svenus.png",
                                            aggregateRating: {
                                                "@type": "AggregateRating",
                                                ratingValue: "4.5",
                                                bestRating: "5",
                                                worstRating: "1",
                                                ratingCount: "876",
                                            },
                                            offers: {
                                                "@type": "Offer",
                                                availability: "https://schema.org/InStock",
                                                price: "0",
                                                priceCurrency: "BDT",
                                            },
                                        },
                                    },
                                ],
                            },
                        ],
                    }),
                }}
            />
            {children}
        </>
    );
}
